import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);
		// declares three int variables that will be used as counters for each of the categories
		int counterOf2 = 0;
		int counterOf3 = 0;
		int counerOf4more = 0;
		// declares double variable that will be used to compute the average number of children
		double sumOftotalchildren = 0;
		// runs the for loop T times
		for (int i = 0; i < T; i++){
			// declares double variable that will be used as a number generator
			double genderNum;
			// declares int variable that will be used as a counter
			int counter = 0;
			// declares two boolean variables that will help determine if boy/girl was already generated
			boolean isBoy = false;
			boolean isGirl = false;
			// runs while loop as long as boy & girl wasn't generated.
			// For values: 0-0.5 it's a boy, for values 0.5-1 it's a girl
			while (isBoy == false | isGirl == false){
				// generates random number using seed & nextDouble 
				genderNum = generator.nextDouble();
				// if the value is under 0.5 == boy
				if (genderNum < 0.5){
					isBoy = true;
				}
				// if the value is over 0.5 == girl
				else {
					isGirl = true;
				}
			// counts every loop to know how many childen was born
			counter++;
			// sums total number of children
			sumOftotalchildren++;
			}
			// counts the categories using the value of counter
			// if the loop ran two times, it adds +1 to countersof2 category
			if (counter == 2)
				counterOf2++;
			// if the loop ran three times, it adds +1 to countersof3 category
			else if (counter == 3)
				counterOf3++;
			// if the loop ran four times or more, it adds +1 to countersof4more category
			else
				counerOf4more++;
			// after checking to which category it was related, resets counter for the next loop check
			counter = 0;
		}
		// prints the average number of children
		System.out.println("Average: " + sumOftotalchildren / T + " children to get at least one of each gender.");
		// prints counters of each category
		System.out.println("Number of families with 2 children: " + counterOf2);
		System.out.println("Number of families with 3 children: " + counterOf3);
		System.out.println("Number of families with 4 or more children: " + counerOf4more);
		// check which counter was the maximum and prints it
		if (counterOf2 >= counterOf3 && counterOf2 >= counerOf4more)
			System.out.println("The most common number of children is 2.");
		else if (counterOf3 >= counterOf2 && counterOf3 >= counerOf4more)
			System.out.println("The most common number of children is 3.");
		else
			System.out.println("The most common number of children is 4 or more.");
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
