import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);
		int counterOf2 = 0;
		int counterOf3 = 0;
		int counerOf4more = 0;
		double sumOftotalchildren = 0;
		for (int i = 0; i < T; i++){
			// declares first random number
			// 0-0.5 boy, 0.5-1 girl
			double genderNum;
			int counter = 0;
			boolean isBoy = false;
			boolean isGirl = false;
			while (isBoy == false | isGirl == false){
				genderNum = generator.nextDouble();
				if (genderNum < 0.5){
					isBoy = true;
				}
				else {
					isGirl = true;
				}
			counter++;
			sumOftotalchildren++;
			}
			if (counter == 2)
				counterOf2++;
			else if (counter == 3)
				counterOf3++;
			else
				counerOf4more++;
			counter = 0;
		}
		System.out.println("Average: " + sumOftotalchildren / T + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + counterOf2);
		System.out.println("Number of families with 3 children: " + counterOf3);
		System.out.println("Number of families with 4 or more children: " + counerOf4more);
		if (counterOf2 >= counterOf3 && counterOf2 >= counerOf4more)
			System.out.println("The most common number of children is 2");
		else if (counterOf3 >= counterOf2 && counterOf3 >= counerOf4more)
			System.out.println("The most common number of children is 3");
		else
			System.out.println("The most common number of children is 4 or more.");
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
